apiVersion: 1

datasources:
  - name: PostgreSQL - Card Games
    type: postgres
    uid: postgres-cards
    url: postgres.postgres.svc.cluster.local:5432
    database: postgresdb
    user: postgresuser
    secureJsonData:
      password: your-password-here
    jsonData:
      sslmode: disable
      maxOpenConns: 5
      maxIdleConns: 2
      connMaxLifetime: 14400
      postgresVersion: 1500
      timescaledb: false
